version: "3.9"

services:
  app:
    build:
      # Use current directory
      context: .
      args:
        - DEV=true
    # Map local port to container port
    ports:
      - "8000:8000"
    # Automatically sync project folder to container folder, like a two way relationship
    # So everything that gets created on local folder goes to container
    # And everything that's created inside the folder in the container goes to our local folder
    volumes:
      - ./app:/app
    # Overrides default command from Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
